### ISSUE TITLE
Shepard et al

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL2019#1]
@akthom + @nniiicc 
- https://github.com/sig-cm/JCDL2019/blob/master/shephard_sigcm_19.docx 

- [x] Overview (2-3 sentence overview of the contribution)
- [x] Feedback (2-3 paragraphs highlighting strengths of the paper. Please note anything that will be valuable for the authors to discuss / present at workshop)

**Comment by nniiicc** [comment]
This paper describes the re-architecting of BCO-DMO's data infrastructure, and in particular their development of an RDF-based Ocean Data Ontology to meet emerging use cases... I think this paper will make an excellent contribution to the workshop. It was well written, and provided a great foundation for others to follow - both in terms of laying out clear motivation, describing methods, and making the practical outcomes accessible to non-experts. My comments below are mostly aimed at helping the rest of the workshop participants get up to speed with the domain you're working in and your contributions.

Targeted feedback:
- In the background you write "Best practices have emerged for data citation, versioning, provenance, and identification while big data challenges stress the capabilities of domain-specific repositories. These progressions required BCO-DMO re-architect its data infrastructure to address software development that had diverged from its conceptual model." ... I don't quite follow what about these emerging best practices required the re-architecting of a repository... I am not saying that skeptically - I just mean I don't quite follow why this necessitated a new repository design. 
- In the presentation at the workshop - I would personally be much more interested in hearing about the backbone ontology you describe, seeing you walk through some use cases, and describe the conceptual foundation from which this builds upon... In other words - the process of *how* the ontology was developed is interesting, but may be more valuable for a paper rather than presentation. Focusing our time and attention at the workshop on conceptual issues that drove your design might be more helpful. 
- Just for a point of reference - Guarino and Welty also describe some of the ideas about modeling and backbone / basic ontologies that you are describing here. It might be useful to note how your process matches or diverges from some of their work. (Guarino, N., & Welty, C. A. (2004). An overview of OntoClean. In Handbook on ontologies (pp. 151-171). Springer, Berlin, Heidelberg. [PDF](https://www.researchgate.net/profile/Nicola_Guarino/publication/285865694_An_overview_of_OntoClean_in_Handbook_on_Ontologies/links/56d0242c08ae85c82346f8f6.pdf) )

**Comment by akthom** [comment]
This is an interesting and well written paper describing the process of re-architecting BCO-DMO’s (a scientific data repository) infrastructure around a conceptual model. This in turn resulted in a re-engineering of the Ocean Data Ontology. 

This is definitely well within  scope for this workshop, and I’m looking forward to talking to the authors more about their work; I’m particularly interested in discussing some of the similarities and differences of conceptual modeling work within scientific repositories vs. digital libraries.  

While the authors do a nice job of explaining their conceptual modeling process, they spend less time talking about how the changes in the model were implemented in the software or the data infrastructure they describe.  It would be great to hear more about how the changes in the ontology were implemented in the infrastructure, and if any challenges arose from that process. Did the architecture/software have any existing conceptual entailments that needed to be navigated around? And were there any “lessons learned” from this work that might informed others taking a data-drive approach to engineering with or re-engineering data architecture?

Minor editing issue  – make sure to spell out “TWC” when it first appears in the text.
