### ISSUE TITLE
Gryk 

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL2019#3]
@kfenlon + @nniiicc 
- https://github.com/sig-cm/JCDL2019/blob/master/gryk_sigcm_19.pdf 

- [x] Overview (2-3 sentence overview of the contribution)
- [x] Feedback (2-3 paragraphs highlighting strengths of the paper. Please note anything that will be valuable for the authors to discuss / present at workshop)

**Comment by kfenlon** [comment]
This is a highly relevant and very well thought-out and written contribution to the workshop, which describes a nested approach to modeling scientific workflows, i.e. an approach that (if I am reading this correctly) nests bioNMR provenance metadata within the PREMIS model of high-level entities.  A strength of this paper that will garner general interest at the workshop is its use of a particular case (modeling biomolecular nuclear magnetic resonance spectroscopy provenance) to explore general themes or patterns in conceptual modeling, such as the necessity of compromise between accuracy and usefulness. 

Some suggestions:

- It is not entirely lucid how these data models are being nested, in a technical or pragmatic or concrete sense. It would be super helpful to include visual examples of both the bioNMR and PREMIS data models and their intersections, for those who are unfamiliar with the data models or their implementations. For example, I am not clear on what it means that the bioNMR model must fragmented to adhere to the PREMIS entities. 
-On that note, interdisciplinarity is both a strength and complication for the workshop as a whole. I imagine it will be hard for all presenters to strike a balance between providing important, domain-specific technical detail on their models and engaging an interdisciplinary audience. I think this paper does really well with that, and visual examples will help get folks on the same page. Perhaps focusing on one or two particularly juicy modeling complications will help with finding this balance.

Thanks very much for a highly interesting contribution!

**Comment by nniiicc** [comment]
(In addition to Katrina's comments above)
I very much enjoyed reading this paper. It was clear, and for the most part I understood it's main contribution as building upon the PREMIS model. 

My feedback is as follows:
- As you note the Premis data model has four types of intellectual entities (but a fifth has been proposed as part of the [V 3.0 revision](http://duraark.eu/wp-content/uploads/2014/10/PREMIS_datamodel.jpg). I wonder why rights wouldn't be appropriate - I am not arguing that they wouldn't be but my mind immediately goes to use cases where they could (e.g. proprietary components of a workflow) 
- Premis has always struck me as being a bit obtuse with its definitions of semantic units (as opposed to metadata elements).... Caplan et al even write at one point "to be a PREMIS purist, you have to think in terms of rather abstract semantic units.  PREMIS semantic units have a direct mapping to the metadata elements defined in the PREMIS XML schema, and may have a less direct mapping to metadata in other schema" [2.1 here](https://www.loc.gov/standards/premis/understanding-premis.pdf) But, knowing that about PREMIS - your nesting made sense to me (while it seemed confusing to Katrina). I think this could be avoided if you took the the time in earlier sections to explain this feature of the PREMIS data model...
- Building on the previous comment - I can't really think of anyone who has done this well. By that I mean, I can't really recall any examples of PREMIS implementations that both explain and demonstrate this modeling feature - I think you have an opportunity to make a nice contribution if you could further flesh that out and use examples from each entity type. 

A general note about revision for future publication:
- This paper is very well written. However, transitions between sections could make for a better reading experience. Right now, your section titles are doing all of the work of signalling to a reader what you're going to talk about next, but the reader is somewhat left to guess why...The `Design Strategy` section for example could be 3x as long and include a further discussion of other relevant models, etc.
