### ISSUE TITLE
Wang, Chang, and Wang - Wuhan contribution. 

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL2019#5]
@akthom + @organisciak 
- https://github.com/sig-cm/JCDL2019/blob/master/wuahn_sigcm_19.pdf

- [x] Overview (2-3 sentence overview of the contribution)
- [x] Feedback (2-3 paragraphs highlighting strengths of the paper. Please note anything that will be valuable for the authors to discuss / present at workshop)

**Comment by organisciak** [comment]
Here are some initial thoughts. I'd love to hear what Andrea thinks - this is relevant to the workshop, though the submission's focus sort of meanders through surface-level discussion while skimming past the conceptual modeling meat.

------

This paper introduces an attribute graph-based model for representing cultural heritage materials. 

This work is potentially relevant to the workshop, but requires more consideration on presentation. You position the graph model as an alternative to RDF or traditional metadata approaches - however, the reasons for the relative weaknesses and strengths are only vaguely discussed.

The other discussion that could be presented and probed more clearly is the generalizability of the approach presented. You write that the Dunhuang grottos project is an *example* of the graph approach, but it's not clear what part of the approach readers can take and apply to their own knowledge organization contexts. The value is stated - improved ability to extract relationship information - but how would you pursue that beyond the CAVE-COMPONENT-OBJECT structure used for the grotto project?

Typo: 'revel knowledge'
Attribution error - This workshop is not part of IW3C2
- Needs an edit - grammatical errors are common; e.g. "when adding or associating new resources, it requires to redesign ontology model when adding or associating new resources"

**Comment by akthom** [comment]
This is definitely a unique case of using ontologies to model cultural heritage data, and I’m looking forward to hearing more from the authors at the workshop.  As it stands this paper is very descriptive, which is appropriate for the length and workshop – but I would encourage the authors to think about how their work relates to other conceptual models and modeling efforts, and to reflect on the unique contributions that this project makes to the work of conceptual modeling. Were there issues unique to this case that reveal something key about conceptual modeling? For instance, the authors must have had to navigate modeling and infrastructuring work in multiple languages; how did they tackle these challenges, and did relying on an ontology/knowledge graph make this easier or harder? What new functionality does the knowledge graph provide that simple keyword search does not? 

Typos – 
Page 1 – Stuides should be Studies
Include reference or URL for “Digital Dunhuang” if there is one

Page 2 – 
“As a step further, these knowledge are” – should be “this knowledge is”
“The platform allow users” – should be “The platform allows users”
“In the following, the research will” – should be “in the future, the research will”


This paper describes the development of a knowledge graph and ontology describing the Dunhuang Grottoes, with the goal of enriching search and analysis of these materials.
