### ISSUE TITLE
Develop Workshop Agenda (timeline)

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL2019#7]
Two weeks in advance of the workshop we should develop an agenda to publish to the website. This should include 

- [x] Time slots for each presentation / activity from start of day to end
- [x] Information about location and logistics of the workshop
- [x] Links to papers and instructions for submitting presentation materials (slides)
- [x] What else... ?

**Comment by kfenlon** [comment]
So these are the activities we promised in our submission, with my comments in bold: 

**Do we have a registration estimate for this yet? We may be able to start the day with more substantial intros to ourselves and attendees if a small group.**

-Presentations: The workshop will begin with the presentation of research or case-studies addressing conceptual issues in digital libraries. Full papers (maximum 6 pages) will have 15 minutes for presentations with 10 minutes for questions and discussion. In-progress papers (maximum 2 pages) will have 10 minutes for presentations with 10 minutes for questions and discussion. Workshop organizers will lead discussions between and at the conclusion of paper presentations.
**-Do we each want to take one or two papers to "chair" (have discussion questions ready for)?**

Keynote: Dr. Karen Wickett will deliver a keynote lecture focused on her work in modeling collection-item level relationships in digital libraries. She will further speak to future research challenges for SIG-CM, including the modeling of identity conditions for complex digital objects.

Roundtables: In the afternoon workshop organizers will lead a series of structured discussion and group breakouts to formalize a set of central research problems for SIG-CM to pursue in the coming years. As a part of this exercise we plan to generate preliminary text for a workshop white paper.
**-I've seen several different ways of structuring this kind of discussion. We could gather take-away questions, themes, or topics from the morning presentations as themes to center afternoon breakouts, or we could brainstorm centering questions/themes in advance. We could do some kind of post-it brainstorming with report-outs from each group, or brainstorming on those giant post-its. In my experience these sessions work best if they're organized around a set of well-defined questions.**

Coordination: Finally, we will end the day by planning further SIG-CM activities, including editing of submitted papers into a special-issue of a Knowledge Organization,Library, Archives, or Information Science journal...

**Comment by nniiicc** [comment]
In line:
- registration estimate - not yet. Just sent query to Downie. 
- I assigned everyone to be a discussant for a paper. I like Katrina's suggestion - since we're allocating a lot of time for each paper let's try to each read and come up with questions. The value (to me) in a workshop paper is that you get substantive feedback and new ideas. Hopefully we can achieve that with 15 minutes of discussion. 
- For the breakout discussion - I don't have a lot of ideas so I'm fully willing to follow someone else's lead here. 
- think we should write a position paper for JASIST. I know that Javed is trying to encourage these as editor, and I think there are some good examples (e.g. https://onlinelibrary.wiley.com/doi/10.1002/asi.24232) Whether or not we take time at the workshop to do this is up for debate - but I think if we're serious about CM as a research agenda we should do this.
